name: Test
on: [push]
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        python -m pip install pytest
    - name: Build and Install
      run: |
        python -m build
        python -m pip install dist/*.whl
    - name: Test with Pytest
      run: |
        python -m pytest 
